samples: samples.tsv
units: units.tsv
contigs: contigs.tsv

outdir: "out"
logdir: "log"

ref:
  name: GRCh38.86
  genome: data/ref/genome.chr21.fa
  genome_idx: data/ref/
  known-variants: data/ref/dbsnp.vcf.gz

filtering:
  # Set to true in order to apply machine learning based recalibration of
  # quality scores instead of hard filtering.
  vqsr: false
  hard:
    # hard filtering as outlined in GATK docs
    # (https://gatkforums.broadinstitute.org/gatk/discussion/2806/howto-apply-hard-filters-to-a-call-set)
    snvs:
      "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0"
    indels:
      "QD < 2.0 || FS > 200.0 || ReadPosRankSum < -20.0"
  depth: "DP < 10"
  
processing:
  remove-duplicates: true
  restrict-regions: data/ref/captured_regions.bed
  # region-padding: 100

params:
  gatk:
    HaplotypeCaller: ""
    BaseRecalibrator: ""
    GenotypeGVCFs: ""
    VariantRecalibrator: ""
  picard:
    MarkDuplicates: "REMOVE_DUPLICATES=true"
  trimmomatic:
    pe:
      trimmer:
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"
    se:
      trimmer:
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"

annotation:
  vep:
    cache: false
    #Indicate the version of the cache if set to true. e.g. 100
    cache_version: 100
    #Indicate the path to the cache files if set to true
    cache_directory: /home/epineiro/Programs/VEP/VEP100/.vep/
    #Indicate assembly version
    assembly: GRCh38
    #Indicate the annotations to include
    annotations: "--sift b --polyphen b --ccds --uniprot --hgvs --symbol --numbers --domains --regulatory --canonical --protein --biotype --uniprot --tsl --af --variant_class --xref_refseq --appris --format vcf"

resources:
    default:
        threads: 1
        mem: 2000
        walltime: 480
    snpeff:
        mem: 8000
        walltime: 480
    call_variants:
        mem: 2000
        threads: 4
        walltime: 480
    combine_calls:
        mem: 2000
        threads: 1
        walltime: 480
    hard_filter_calls:
        mem: 2000
        walltime: 480
    trim_reads:
        mem: 2000
        threads: 16
        walltime: 480
    map_reads:
        mem: 2000
        threads: 8
        walltime: 480
    recalibrate_base_qualities:
        mem: 2000
        walltime: 480
    mark_duplicates:
        mem: 2000
        walltime: 480
    vep:
        mem: 2000
        threads: 32
        walltime: 480
